version: '3'
services:
  back:
    image: 7f834f7d5fcc
    ports:
    - "8080:8080"
    environment: 
    - ENVIRONMENT=dev

  front:
    image: e0fa0ea16bc4
    ports:
    - "8081:8081"
    environment:
    - APP_PORT=8081
    - WS_BACK_URL=172.17.0.1

  
   
